### ISSUE TITLE
`Shrink selection` while nothing is selected causes cursor to jump to last position where `Expand selection` was used

### ISSUE THREAD

**Issue by reuben** [Gregoor/soy#5]
**STR:**

In a TSX file, with e.g. the following contents:

```js
import { sum } from 'lodash-es';
import React, { SetStateAction } from 'react';
```

Put the cursor at the end of the first `import`, then use `Expand selection`. Now, move the cursor, which will cause the selection to be dismissed. Finally, use `Shrink selection`.

**Results:**

Cursor jumps back to end of the first `import`.

**Expected results:**

Nothing happens to the cursor when there's no selection to shrink.

**Comment by Gregoor** [comment]
Fixed in `2.0.4`
